# Based on:
# - godot-export documentation : https://github.com/firebelley/godot-export
# - bitbrain's tutorial: https://bitbra.in/2020/08/01/publish-godot-game-to-itchio.html

on:
  push:
    tags:
      - 'v*'

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - name: get tag from version
        id: tag_version
        run: |
          echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}
      - name: export game
        uses: firebelley/godot-export@v2.4.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/mono/Godot_v3.2.3-stable_mono_linux_headless_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/mono/Godot_v3.2.3-stable_mono_export_templates.tpz
          relative_project_path: ./
          create_release: true
          base_version: ${{ steps.tag_version.outputs.TAG_VERSION}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}