on:
  release:
    types: [published]

jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: fetch game
        id: fetch-web
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: rexy-haunted-bakery-web.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
      - name: deploy to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_TOKEN }}
          CHANNEL: web
          ITCH_GAME: rexy-haunted-bakery
          ITCH_USER: swynfel
          PACKAGE: rexy-haunted-bakery-web.zip
          VERSION: ${{ steps.fetch-web.outputs.version }}
